services:
  app_proxy:
    environment:
      APP_HOST: schjonhaug-kanari_web_1
      APP_PORT: 3000

  backend:
    build:
      context: https://github.com/schjonhaug/kanari.git#main:backend
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      KANARI_NETWORK: mainnet
      KANARI_ELECTRUM_URL: tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT
      KANARI_BIND_ADDRESS: 0.0.0.0:3000
      KANARI_WALLET_DIR: /app/data/wallets
      KANARI_METADATA_DB: /app/data/metadata.sqlite
    volumes:
      - ${APP_DATA_DIR}/backend:/app/data

  web:
    build:
      context: https://github.com/schjonhaug/kanari.git#main:frontend
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NEXT_PUBLIC_API_URL: http://schjonhaug-kanari_backend_1:3000
    depends_on:
      - backend
