services:
  backend:
    build:
      context: https://github.com/schjonhaug/kanari.git#main:backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - KANARI_NETWORK=mainnet
      - KANARI_ELECTRUM_URL=$APP_KANARI_ELECTRUM_URL
      - KANARI_BIND_ADDRESS=0.0.0.0:3000
      - KANARI_WALLET_DIR=/app/data/wallets
      - KANARI_METADATA_DB=/app/data/metadata.sqlite
    volumes:
      - ${APP_DATA_DIR}/backend:/app/data
    networks:
      - kanari-network
    expose:
      - 3000

  frontend:
    build:
      context: https://github.com/schjonhaug/kanari.git#main:frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - kanari-network
    expose:
      - 3000

  app_proxy:
    environment:
      - APP_HOST=schjonhaug-kanari_frontend_1
      - APP_PORT=3000

networks:
  kanari-network:
    driver: bridge