version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_KANARI_WEB_IP
      APP_PORT: 3000

  backend:
    build:
      context: https://github.com/schjonhaug/kanari.git#main:backend
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    networks:
      default:
        ipv4_address: $APP_KANARI_BACKEND_IP
    environment:
      KANARI_NETWORK: mainnet
      KANARI_ELECTRUM_URL: $APP_ELECTRS_NODE_IP:$APP_ELECTRS_TCP_PORT
      KANARI_BIND_ADDRESS: 0.0.0.0:3000
      KANARI_WALLET_DIR: /app/data/wallets
      KANARI_METADATA_DB: /app/data/metadata.sqlite
    volumes:
      - ${APP_DATA_DIR}/backend:/app/data

  web:
    build:
      context: https://github.com/schjonhaug/kanari.git#main:frontend
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    networks:
      default:
        ipv4_address: $APP_KANARI_WEB_IP
    environment:
      NEXT_PUBLIC_API_URL: http://$APP_KANARI_BACKEND_IP:3000
    depends_on:
      - backend