version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: schjonhaug-canary_web_1
      APP_PORT: 3000
      PROXY_AUTH_WHITELIST: "/api/*"

  backend:
    build:
      context: https://github.com/schjonhaug/canary.git#main:backend
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      CANARY_NETWORK: mainnet
      CANARY_ELECTRUM_URL: tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT
      CANARY_BIND_ADDRESS: 0.0.0.0:3001
      CANARY_WALLET_DIR: /app/data/database/mainnet/wallets
      CANARY_METADATA_DB: /app/data/database/mainnet/metadata.sqlite
      # FOSS mode - disable authentication
      CANARY_ENABLE_AUTH: "false"
      # Optional notification providers (ntfy is enabled by default)
      CANARY_ENABLE_NTFY: "true"
      CANARY_ENABLE_TWILIO: "false"
    volumes:
      - ${APP_DATA_DIR}/database:/app/data/database

  web:
    build:
      context: https://github.com/schjonhaug/canary.git#main:frontend
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      # Backend API URL for the Next.js proxy
      NEXT_PUBLIC_API_URL: http://schjonhaug-canary_backend_1:3001
    depends_on:
      - backend
